### ISSUE TITLE
User history filtered by specific key (favorite)

### ISSUE THREAD

**Issue by migmake** [doublesecretagency/craft-upvote#15]
I made a special key vote to implement the Favorite feature : 
`{{ craft.upvote.upvote(entry.id, 'favorite') }}`

So when I call userHistory() it works but I got both the general upvote/downvote and the favorite vote :
3686:favorite => 1
3686 => 1
3706 => -1
3677 => -1

```
{% set userVotes = craft.upvote.userHistory() %}
{% for key, value in userVotes %}
  {{ key }} => {{ value }}<br>
{% endfor %}
```

So my question  is : 
Can I filter the userHistory with a specific key?  To only display the votes for this favorite key.
(as it is possible to filter for the function Sort by highest voted)

**Comment by lindseydiloreto** [comment]
Hi @migswd,

Instead of looping over the `userVotes` object, just treat it as an _associative array_...

```twig
{% set voteKey = entry.id ~ ':favorite' %}

{{ userVotes[voteKey] }}
```

That will output `1`, which represents an upvote. (A downvote is represented by `-1`.)

If there's a chance that a user has not yet favorited an item, you may want to include a fallback value...

```twig
{{ userVotes[voteKey] ?? 'no favorite' }}
```

Hope that helps! 🙂
